image: node:16

pipelines:
  default:
    - parallel:
      - step:
          name: Build Admin
          caches:
            - node
          script:
            - cd admin
            - npm install --legacy-peer-deps
            - npm run build
      - step:
          name: Build Frontend
          caches:
            - node
          script:
            - cd frontend
            - npm install --legacy-peer-deps
