global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'nginx'
    # Scrapes the Nginx Exporter sidecar
    static_configs:
      - targets: ['nginx-exporter:9113']
        
  - job_name: 'prometheus'
    # Promethues internal metrics
    static_configs:
      - targets: ['localhost:9090']
